enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('enquete/<int:pk>/votacao',
        views.votacao, name='votacao'
    ),
]

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime


class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de publicacao')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora



class Opcao(models.Model):
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

enquete/main/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao



class IndexView(generic.ListView):
    context_object_name = 'ultimas_perguntas'
    template_name = 'main/index.html'
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
            ).order_by('-data_publicacao')[:5]



class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'main/detalhes.html'
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())



class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'




def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {'pergunta': pergunta,'error_message': "Selecione uma opcão válida"})
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('main:resultado', args=(pergunta.id,)))

enquete/main/templates/main/detalhes.html
<html>
    <head>
        <title>App Enquete</title>
        <body>
         <h2>Detalhes da Enquete {{ pergunta.id }}</h2>

         {% for autor in autor %}
        <li><u>Nome:</u><a href="{% url 'main:lista_autor' %}">{{ autor.nome }}</a> <u>Cidade:</u> {{ autor.cidade }} <u>Email:</u> {{ autor.email }}</li> 
         {% endfor %}
         <p>
         <u>Pergunta</u>: {{ pergunta.texto }}<br>
         <u>Data de publicação</u>: {{ pergunta.data_publicacao }} 



         {% if error_message %}
         <hr>
         

         <strong>{{ error_message }}</strong>
         <hr/>
         {% endif %}
         
         <form action = "{% url 'main:votacao' pergunta.id %}" method = "post">
         {% csrf_token %}

         <ul>
             {% for opcao in pergunta.opcao_set.all %}
                 <li><input type ="radio" name="opcao" id="opcao{{ foloop.counter }}" value="{{ opcao.id }}">
                 <label for="opcao{{ foloop.counter }}"> {{ opcao.texto }} 
                 </li>

             {% endfor %}
            
              

         </ul>
         <input type ="submit" value="Registre seu voto">
  </form>
  <hr>
  <a href ="{% url 'main:index' %}">Retorne a página principal</a>
        </body>
    </head>
</html>

enquete/main/templates/main/index.html
<html>

    <head>
        <title>App Enquete</title>

        <body>
            {% if ultimas_perguntas %}
            <h2>Lista das Últimas enquetes</h2>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                <li><a href = "{% url 'main:detalhes' pergunta.id %}">{{ pergunta.texto }}</a>(<a href="{% url 'main:resultado' pergunta.id %}">Ver parcial</a>)</li>

                {% endfor %}
            </ul>
            {% else %}
            <p>Não há enquetes cadastras até o momento</p>
            {% endif %}
        </body>
    </head>
</html>

enquete/main/templates/main/lista_autor.html
<html>
    <head>
        <title>App Enquete</title>
        <body>
         <h2>Lista Enquete de autores</h2>
        
         {% for lista in lista %}
         
            <li><u>Nome:</u>{{ lista.nome }} <u>Cidade:</u>{{ lista.cidade }} <u>Email:</u>{{ lista.email }}</li>

           {% endfor %}
       
         
          {% if ultimas_perguntas %}
       
            <ul>
                {% for pergunta in ultimas_perguntas %}
                <li>{{ pergunta.texto }}</a></li>

                {% endfor %}
            </ul>
            {% else %}
            <p>Não há enquetes cadastras até o momento</p>
            {% endif %}
  <hr>
 
  <a href ="{% url 'main:index' %}">Retorne a página principal</a>
        </body>
    </head>
</html>

enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>App Enquete</title>
        <body>
            <h2>Resultado parcial da Enquete {{ pergunta.id }}</h2>
            <u>Pergunta</u>: {{ pergunta.texto }}<br>
         <u>Data de publicação</u>: {{ pergunta.data_publicacao }}

         <ul>
             {% for opcao in pergunta.opcao_set.all %}
                 <li>{{ opcao.texto }} = {{ opcao.votos }} voto{{ opcao.votos | pluralize }}</li>
             {% endfor %}

         </ul>
         <hr/>
         <a href="{% url 'main:detalhes' pergunta.id %}">Deseja votar novamente?</a> |
         <a href="{% url 'main:index' %}">Retornar à página principal</a>

        </body>
    </head>
</html>